spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

ignore:
  urls:
  - /**/*.css
  - /auth/**
  - /admin/user/mobile/**
  - /refresh/**
  - /swagger-ui.html
  - /swagger-resources/**
  - /*/v2/api-docs
  - /webjars/**
  - /doc.html

swagger:
  client:
    - panda-user-service
    - panda-gen-service
# 关闭默认路由
zuul:
  ignoredServices: '*'
